services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
